services:
  otterwiki:
    image: redimp/otterwiki:2
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app-data:/app-data
    environment:
      SITE_NAME: "Honyaku Wiki"
      SITE_DESCRIPTION: "API & Task Documentation Wiki"
