services:
  otterwiki:
    image: redimp/otterwiki:2
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app-data:/app-data
    environment:
      SITE_NAME: "Honyaku Wiki"
      SITE_DESCRIPTION: "API & Task Documentation Wiki"
      READ_ACCESS: "ANONYMOUS"
      WRITE_ACCESS: "ANONYMOUS"
      ATTACHMENT_ACCESS: "ANONYMOUS"
      UPLOAD_ACCESS: "ANONYMOUS"
      EMAIL_NEEDS_CONFIRMATION: "False"
      AUTO_APPROVAL: "True"
