services:
  otterwiki:
    image: redimp/otterwiki:2
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app-data:/app-data
    environment:
      SITE_NAME: "Honyaku Wiki"
      SITE_DESCRIPTION: "API & Task Documentation Wiki"
      # Permissions: READ, WRITE, ATTACHMENT, UPLOAD
      # Options: ANONYMOUS, REGISTERED, APPROVED, ADMIN
      READ_ACCESS: "REGISTERED"
      WRITE_ACCESS: "REGISTERED"
      ATTACHMENT_ACCESS: "REGISTERED"
      # Registration settings
      AUTO_APPROVAL: "False"
      EMAIL_NEEDS_CONFIRMATION: "True"
      NOTIFY_ADMINS_ON_REGISTER: "True"
